apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "handle-worker.fullname" . }}
  labels:
    {{- include "handle-worker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "handle-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "handle-worker.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "handle-worker.fullname" . }}
      containers:
        - name: {{ .Values.containerName | default (include "handle-worker.name" .) }}
          image: {{ include "handle-worker.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
