apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret-key
  labels:
    app.kubernetes.io/part-of: ecom-stack
type: Opaque
stringData:
  Jwt__SecretKey: {{ .Values.jwt.secretKey | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-issuer
  labels:
    app.kubernetes.io/part-of: ecom-stack
type: Opaque
stringData:
  Jwt__Issuer: {{ .Values.jwt.issuer | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-audience
  labels:
    app.kubernetes.io/part-of: ecom-stack
type: Opaque
stringData:
  Jwt__Audience: {{ .Values.jwt.audience | quote }}
