replicaCount: 1

image:
  repository: ecom/handle-worker
  tag: ""
  pullPolicy: IfNotPresent

containerName: handle-worker

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

env:
  ConnectionStrings__BusinessConnection: "Server=ecom-stack-mysqlbusiness.ecom.svc.cluster.local;Port=3306;Database=business_db;User=root;Password=P@ssw0rd123;"
  Kafka__BootstrapServers: "kafka.ecom.svc.cluster.local:9092"
  Kafka__Topic: "order-created"
  Kafka__GroupId: "handle-worker-group"

serviceAccount:
  create: true
